
== Usage

This is based on:

https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient

but we extend it so that the top `n` predicted ranks are matched against the actual ranks even if an actual rank is not in the top `n`

=== List the available cells

----
$ python list_cells.py summary_predicted.all.tsv | column
CO-006  CO-039  CO-060  CO-118  CO-153  CO-173  CR-010  HN-045  HN-064  HN-158  HN-185  HN-244
CO-017  CO-042  CO-066  CO-119  CO-161  CO-174  CR-029  HN-049  HN-067  HN-161  HN-235  HN-252
CO-031  CO-045  CO-071  CO-120  CO-163  CO-175  CR-034  HN-051  HN-069  HN-179  HN-237  HN-264
CO-034  CO-049  CO-103  CO-152  CO-171  CR-007  HN-044  HN-052  HN-144  HN-184  HN-239
----

=== Run a single Spearman

See:

----
$ python do_spearman.py -h
----

E.g.,

----
$ python do_spearman.py summary_predicted.all.tsv CR-029 3
original dataframe length: 1269
mae:       3.667
spearman:  0.750
----

=== Run Spearman for all cells

=== Clustered Spearman

First, cluster the predicted records.  If two records have an AUC difference that is less than the average stddev of the pair, their effective rank is replaced (clustered) by the average of their ranks.  This is applied for clusters of any size.

Then, we apply Spearman on the effective ranks.

Original data:

----
        1          2       3       4  cluster_rank
0  HN-235   Drug_194  0.3997  0.0514      1.333333
1  HN-235   Drug_988  0.4166  0.0443      1.500000
2  HN-235  Drug_1105  0.5291   0.074      2.000000
3  HN-235  Drug_1127   0.532  0.0943      1.500000

mae:       2.083
spearman:  0.775
----

Modified data row 0, column 3 (the mean AUC for HN-235 x Drug_988):

----
        1          2       3       4  cluster_rank
0  HN-235   Drug_988  0.3990  0.0443      1.333333
1  HN-235   Drug_194  0.3997  0.0514      1.333333
2  HN-235  Drug_1105  0.5291   0.074      2.500000
3  HN-235  Drug_1127   0.532  0.0943      1.500000

mae:       2.125
spearman:  0.775
----

Note that the ordering has changed, the MAE has changed, but the Spearman has not, because the records 0 and 1 were clustered because the small difference in means was within the range of their stddevs.
